version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        patterns:
          - "@playwright*"
          - "@types*"
          - "@vitejs*"
          - "oxlint"
          - "tailwindcss"
          - "@tailwindcss*"
          - "typescript"
          - "vite"
